# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 774f066354f0bf7f42e330e93954a2c1d19cf81e27e829f37326b846c3c82cdead34de9cc18a781af107b806dba826b6fa1d5da37d8374943b94bf66ec74818f

test:
  secret_key_base: ff4e47292514fa7f0268b7fdaae8746127773c7d52532c3922056e88528c39a062093b421c43f4688ed9b5a1ce2ee9230c81c04c14ef38e8efbe2d73efc71136

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
